ai/urls.py
from django.urls import path

app_name = 'ai'

urlpatterns = [
    # path('detail/', AlarmDetailView.as_view(), name='alarm-detail'),
    # path('detail/api/<int:page>/', AlarmPagiNationAPIView.as_view()),
    # path('detail/agree/api/', AlarmAgreeAPIView.as_view()),
    # path('detail/deny/api/', AlarmDenyAPIView.as_view()),
    # path('detail/cancel/api/', AlarmCancelAPIView.as_view())
]

member/urls.py
from django.urls import path

from member.views import MemberJoinView, MemberCheckIdView, MemberLoginView, SendVerificationCodeView, \
    MemberNormalJoinView, MemberIdSearchView, MemberResetPasswordView, MemberActivateEmailView, MemberMainView, \
    AdminMemberLoginView, AdminMainView, AdminMainUserView, AdminMainUserListAPI, AdminMainNotificationView, \
    AdminNotificationListAPI, AdminMainExhibitionView, AdminMainExhibitionListAPI, soft_delete, soft_delete_exhibition, \
    translate, AdminMainLogoutView

app_name = 'member'

urlpatterns = [
    path('join/', MemberJoinView.as_view(), name='join'),
    path('join-normal/', MemberNormalJoinView.as_view(), name='join-normal'),
    path('login/', MemberLoginView.as_view(), name='login'),
    path('check-id/', MemberCheckIdView.as_view(), name='check-id'),
    path('activate/<str:school>', SendVerificationCodeView.as_view(), name='activate'),
    path('account-find/', MemberIdSearchView.as_view(), name='account-find'),
    path('account-activate/<str:email>', MemberActivateEmailView.as_view(), name='account-activate'),
    path('account-reset/<int:id>/<str:random>/',MemberResetPasswordView.as_view(), name='account-reset'),
#     관리자 path 추가
    path('admin_login/', AdminMemberLoginView.as_view(), name='admin_login'),
    path('admin_main/', AdminMainView.as_view(), name='admin_main'),
    path('admin_main_user/', AdminMainUserView.as_view(), name='admin_main_user'),
    path('admin_main_user/<int:page>/', AdminMainUserListAPI.as_view(), name='admin_main_user_list'),
    path('admin_main_notification/', AdminMainNotificationView.as_view(), name='admin_main_notification'),
    path('admin_main_notification/<int:page>/', AdminNotificationListAPI.as_view(), name='admin_main_notification_list'),
    path('admin_main_exhibition/', AdminMainExhibitionView.as_view(), name='admin_main_exhibition'),
    path('admin_main_exhibition/<int:page>/', AdminMainExhibitionListAPI.as_view(), name='admin_main_exhibition_list'),
    path('soft_delete/', soft_delete, name='soft_delete'),
    path('soft_delete_exhibition/', soft_delete_exhibition, name='soft_delete_exhibition'),
    path('translate/', translate, name='translate'),
    path('admin_main_logout/', AdminMainLogoutView.as_view(), name='admin_logout')
]

oneLabProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from exhibition.views import ExhibitionFileDownloadView
from oneLabProject.views import MainView
from share.views import ShareDownloadView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('oauth.urls')),
    path('onelab/', include('onelab.urls')),
    path('community/', include('community.urls')),
    path('myPage/', include('myPage.urls')),
    path('point/', include('point.urls')),
    path('alarm/', include('alarm.urls')),
    path('replies/', include('reply.urls')),
    path('place/', include('place.urls')),
    path('school/', include('school.urls')),
    path('review/', include('review.urls')),
    path('share/', include('share.urls')),
    path('upload/<path:file_path>', ShareDownloadView.as_view(), name='download'),
    path('exhibition/', include('exhibition.urls')),
    path('upload/<path:file_path>/', ExhibitionFileDownloadView.as_view(), name='exhibition-down'),
    path('notification/', include('notification.urls')),
    path('', MainView.as_view(), name='main'),
    path('ai/api/', include('ai.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

point/urls.py
from django.urls import path

from point.views import PointView, PointListView, PointListDetailView, PointUseListView, \
    PointUseDetailView, PointDetailView, PointGetListView, PointGetDetailView

app_name = 'point'

urlpatterns = [
    path('new/', PointView.as_view(), name='new'),
    path('list/', PointListView.as_view(), name='list'),
    path('use/',PointUseListView.as_view(), name='use'),
    path('useDetail/',PointUseDetailView.as_view(), name='useDetail'),
    path('detail/<int:price>/', PointDetailView.as_view(), name='detail'),
    path('get/',PointGetListView.as_view(), name='get'),
    path('getDetail/',PointGetDetailView.as_view(), name='getDetail'),
    path('detail/', PointListDetailView.as_view(), name='detaillist')

]

templates/header/main-page-header-all.html
{% extends 'login/base.html' %}
{% load static %}

{% block title %}로그인{% endblock %}
{% block content %}
    <!--헤더-->
        <div class="web-header">
            <div class="web-header-large">
                <header class="header-wrapper">
                    <div class="header-container">
                        <h1 class="wadiz-logo">
                            <a href="">
                                <span class="label">원랩</span>
                                <img id="one-lab" src="{% static 'public/images/header-logo_RE.png' %}" alt="" />
                            </a>
                        </h1>
                        <!--메뉴 탭-->
                        <ul class="desktop-container">
                            <!--원랩-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>원랩</span></a>
                            </li>
                            <!--공지-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>공지</span></a>
                            </li>
                            <!--장소공유-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>장소공유</span></a>
                            </li>
                            <!--커뮤니티-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>커뮤니티</span></a>
                            </li>
                            <!--학교-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>학교</span></a>
                            </li>
                        </ul>
                        <div class="web-header-utils">
                            <!--검색창-->
                            <div class="desktop-search-app-container">
                                <form>
                                    <div class="search-controller-container" tabindex="-1">
                                        <div class="search-tag-empty-tag"></div>
                                        <div class="search-controller-keyword">
                                            <input
                                                type="search"
                                                placeholder="새로운 일상이 필요하신가요?"
                                                aria-label="검색"
                                                value=""
                                            />
                                        </div>
                                        <button type="submit" class="search-controller-search-icon" aria-label="검색">
                                            <svg
                                                viewBox="0 0 40 40"
                                                focusable="false"
                                                role="presentation"
                                                class="withicon-icon"
                                                aria-hidden="true"
                                                style="width: 24px; height: 24px;"
                                            >
                                                <path fill="none" d="M0 0h40v40H0z"></path>
                                                <path
                                                    d="M29.2 27.91a14.38 14.38 0 1 0-1.42 1.4l7.16 7.15.07.08 1.41-1.41zM18.45 6a12.36 12.36 0 0 1 8.35 3.23 12.24 12.24 0 0 1 4 8.59A12.39 12.39 0 1 1 17.88 6z"
                                                ></path>
                                            </svg>
                                        </button>
                                    </div>
                                </form>
                            </div>
                           <!--로그인 회원가입-->
                            <div class="header-desktop-user">
                                <div class="user-container">
                                    <button type="button" class="user-btn-sign" onclick="location.href='{% url 'member:login' %}'">로그인</button
                                    ><button data-event="iam.signup" class="user-btn-sign" onclick="location.href='/member/join-normal/'">회원가입</button>
                                </div>
                            </div>
                            <!--포인트 충전-->
                            <div class="charge-point">
                                <button aria-label="포인트 충전" class="charge-point-button" type="button" onclick="location.href='/point/new/'" >
                                    <span><span class="button-children">포인트 충전</span></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </header>
            </div>
        </div>
        <!--헤더 상세 컨텐츠-->
        <div class="main-wrapper-content"></div>
        <div>
            <div class="categorybar-container">
                <div class="categorybar-main-categories-wrapper">
                    <ul class="categorybar-main-categories">
                        <li class="categorybar-main-category">장소공유목록</li>
                        <li class="categorybar-main-category">원랩목록</li>
                        <li class="categorybar-main-category">질의응답</li>
                        <li class="categorybar-main-category">자료공유</li>
                        <li class="categorybar-main-category">공모전·대회</li>
                        <li class="categorybar-main-category">회사소개</li>
                    </ul>
                </div>
            </div>
        </div>
{% endblock %}

templates/header/main-page-header.html
{% extends 'login/base.html' %}
{% load static %}

{% block title %}로그인{% endblock %}
{% block content %}
    <!--헤더-->
        <div class="web-header">
            <div class="web-header-large">
                <header class="header-wrapper">
                    <div class="header-container">
                        <h1 class="wadiz-logo">
                            <a href="">
                                <span class="label">원랩</span>
                                <img id="one-lab" src="{% static 'public/images/header-logo_RE.png'%}" alt="" />
                            </a>
                        </h1>
                        <!--메뉴 탭-->
                        <ul class="desktop-container">
                            <!--원랩-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>원랩</span></a>
                            </li>
                            <!--공지-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>공지</span></a>
                            </li>
                            <!--장소공유-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>장소공유</span></a>
                            </li>
                            <!--커뮤니티-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>커뮤니티</span></a>
                            </li>
                            <!--학교-->
                            <li class="desktop-item">
                                <a class="desktop-link" href=""><span>학교</span></a>
                            </li>
                        </ul>
                        <div class="web-header-utils">
                            <!--검색창-->
                            <div class="desktop-search-app-container">
                                <form>
                                    <div class="search-controller-container" tabindex="-1">
                                        <div class="search-tag-empty-tag"></div>
                                        <div class="search-controller-keyword">
                                            <input
                                                type="search"
                                                placeholder="새로운 일상이 필요하신가요?"
                                                aria-label="검색"
                                                value=""
                                            />
                                        </div>
                                        <button type="submit" class="search-controller-search-icon" aria-label="검색">
                                            <svg
                                                viewBox="0 0 40 40"
                                                focusable="false"
                                                role="presentation"
                                                class="withicon-icon"
                                                aria-hidden="true"
                                                style="width: 24px; height: 24px;"
                                            >
                                                <path fill="none" d="M0 0h40v40H0z"></path>
                                                <path
                                                    d="M29.2 27.91a14.38 14.38 0 1 0-1.42 1.4l7.16 7.15.07.08 1.41-1.41zM18.45 6a12.36 12.36 0 0 1 8.35 3.23 12.24 12.24 0 0 1 4 8.59A12.39 12.39 0 1 1 17.88 6z"
                                                ></path>
                                            </svg>
                                        </button>
                                    </div>
                                </form>
                            </div>
                           <!--로그인 회원가입-->
                            <div class="header-desktop-user">
                                <div class="user-container">
                                    <button type="button" class="user-btn-sign" onclick="location.href={% url 'member:login' %}">로그인</button
                                    ><button data-event="iam.signup" class="user-btn-sign">회원가입</button>
                                </div>
                            </div>
                            <!--포인트 충전-->
                            <div class="charge-point">
                                <button aria-label="포인트 충전" class="charge-point-button" type="button" onclick="location.href={% url 'point:new' %}" >
                                    <span><span class="button-children">포인트 충전</span></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </header>
            </div>
        </div>
{% endblock %}