ai/urls.py
from django.urls import path

app_name = 'ai'

urlpatterns = [
    # path('detail/', AlarmDetailView.as_view(), name='alarm-detail'),
    # path('detail/api/<int:page>/', AlarmPagiNationAPIView.as_view()),
    # path('detail/agree/api/', AlarmAgreeAPIView.as_view()),
    # path('detail/deny/api/', AlarmDenyAPIView.as_view()),
    # path('detail/cancel/api/', AlarmCancelAPIView.as_view())
]

member/urls.py
from django.urls import path

from member.views import MemberJoinView, MemberCheckIdView, MemberLoginView, SendVerificationCodeView, \
    MemberNormalJoinView, MemberIdSearchView, MemberResetPasswordView, MemberActivateEmailView, MemberMainView, \
    AdminMemberLoginView, AdminMainView, AdminMainUserView, AdminMainUserListAPI, AdminMainNotificationView, \
    AdminNotificationListAPI, AdminMainExhibitionView, AdminMainExhibitionListAPI, soft_delete, soft_delete_exhibition, \
    translate, AdminMainLogoutView

app_name = 'member'

urlpatterns = [
    path('join/', MemberJoinView.as_view(), name='join'),
    path('join-normal/', MemberNormalJoinView.as_view(), name='join-normal'),
    path('login/', MemberLoginView.as_view(), name='login'),
    path('check-id/', MemberCheckIdView.as_view(), name='check-id'),
    path('activate/<str:school>', SendVerificationCodeView.as_view(), name='activate'),
    path('account-find/', MemberIdSearchView.as_view(), name='account-find'),
    path('account-activate/<str:email>', MemberActivateEmailView.as_view(), name='account-activate'),
    path('account-reset/<int:id>/<str:random>/',MemberResetPasswordView.as_view(), name='account-reset'),
#     관리자 path 추가
    path('admin_login/', AdminMemberLoginView.as_view(), name='admin_login'),
    path('admin_main/', AdminMainView.as_view(), name='admin_main'),
    path('admin_main_user/', AdminMainUserView.as_view(), name='admin_main_user'),
    path('admin_main_user/<int:page>/', AdminMainUserListAPI.as_view(), name='admin_main_user_list'),
    path('admin_main_notification/', AdminMainNotificationView.as_view(), name='admin_main_notification'),
    path('admin_main_notification/<int:page>/', AdminNotificationListAPI.as_view(), name='admin_main_notification_list'),
    path('admin_main_exhibition/', AdminMainExhibitionView.as_view(), name='admin_main_exhibition'),
    path('admin_main_exhibition/<int:page>/', AdminMainExhibitionListAPI.as_view(), name='admin_main_exhibition_list'),
    path('soft_delete/', soft_delete, name='soft_delete'),
    path('soft_delete_exhibition/', soft_delete_exhibition, name='soft_delete_exhibition'),
    path('translate/', translate, name='translate'),
    path('admin_main_logout/', AdminMainLogoutView.as_view(), name='admin_logout')
]

notification/urls.py
from django.urls import path

from notification.views import NotificationWriteView, NotificationDetailView, NotificationListView, NotificationListAPI, \
    NotificationUpdateView

app_name = 'notification'

urlpatterns = [
    path('write/', NotificationWriteView.as_view(), name='write'),
    path('detail/', NotificationDetailView.as_view(), name='detail'),
    path('list/', NotificationListView.as_view(), name='list'),
    path('list/<int:page>/', NotificationListAPI.as_view(), name='list-api'),
    path('update/<int:id>/', NotificationUpdateView.as_view(), name='update')
]

oneLabProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from exhibition.views import ExhibitionFileDownloadView
from oneLabProject.views import MainView
from share.views import ShareDownloadView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('oauth.urls')),
    path('onelab/', include('onelab.urls')),
    path('community/', include('community.urls')),
    path('myPage/', include('myPage.urls')),
    path('point/', include('point.urls')),
    path('alarm/', include('alarm.urls')),
    path('replies/', include('reply.urls')),
    path('place/', include('place.urls')),
    path('school/', include('school.urls')),
    path('review/', include('review.urls')),
    path('share/', include('share.urls')),
    path('upload/<path:file_path>', ShareDownloadView.as_view(), name='download'),
    path('exhibition/', include('exhibition.urls')),
    path('upload/<path:file_path>/', ExhibitionFileDownloadView.as_view(), name='exhibition-down'),
    path('notification/', include('notification.urls')),
    path('', MainView.as_view(), name='main'),
    path('ai/api/', include('ai.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/models.py
from django.db import models

from file.models import File
from notification.managers import NotificationManager
from oneLabProject.models import Period


class Notification(Period):
    NOTIFICATION_STATUS = [
        (0, '커뮤니티'),
        (1, '원랩'),
        (2, '장소공유'),
        (3, '대회공모전')
    ]
    notification_title = models.CharField(null=False, blank=False, max_length=30)
    notification_content = models.CharField(null=False, blank=False, max_length=2000)
    notification_view_count = models.IntegerField(null=False, blank=False, default=0)
    notification_status = models.SmallIntegerField(choices=NOTIFICATION_STATUS, default=0)
    # True=게시 중, False=게시 종료
    notification_post_status = models.BooleanField(null=False, default=True)

    objects = models.Manager()
    enabled_objects = NotificationManager()

    class Meta:
        db_table = 'tbl_notification'
        ordering = ['-id']

    def get_absolute_url(self):
        return f'/notification/detail/?id={self.id}'

class NotificationFile(Period):
    file = models.ForeignKey(File, primary_key=True, on_delete=models.PROTECT, null=False)
    path = models.ImageField(null=False, blank=False, upload_to='notification/%Y/%m/%d')
    notification = models.ForeignKey(Notification, on_delete=models.PROTECT, null=False)

    class Meta:
        db_table = 'tbl_notification_file'

notification/views.py
from django.db import transaction
from django.db.models import Q, Subquery, OuterRef
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.response import Response
from rest_framework.views import APIView

from file.models import File
from notification.models import Notification, NotificationFile


class NotificationWriteView(View):
    def get(self, request):
        return render(request, 'notification/write.html')

    @transaction.atomic
    def post(self, request):
        data = request.POST
        file = request.FILES

        data = {
            'notification_title': data['notification-title'],
            'notification_content': data['notification-content'],
            'notification_status': data['notification-status']
        }

        notification = Notification.objects.create(**data)

        for key, file in request.FILES.items():
            file_instance = File.objects.create(file_size=file.size)
            NotificationFile.objects.create(file=file_instance, path=file, notification=notification)

        return redirect(notification.get_absolute_url())


class NotificationDetailView(View):
    def get(self, request):
        notification = Notification.objects.get(id=request.GET['id'])

        notification.notification_view_count += 1
        notification.save(update_fields=['notification_view_count'])

        context = {
            'notification' : notification,
            'notification_file' : list(notification.notificationfile_set.all())
        }

        return render(request, 'notification/detail.html', context)

class NotificationListView(View):
    def get(self, request):
        return render(request, 'notification/list.html')


class NotificationListAPI(APIView):
    def get(self, request, page):
        row_count=5

        offset = (page -1) *  row_count
        limit = page * row_count

        columns = [
            'id',
            'notification_title',
            'notification_content',
            'notification_view_count',
            'notification_status',
            'created_date',
            'notification_file'
        ]

        category = request.GET.get('category', 0)
        type = request.GET.get('type', '')
        keyword = request.GET.get('keyword', '')

        condition = Q()
        if type:
            for t in list(type):
                if t == 't':
                    condition |= Q(notification_title__icontains=keyword)

                elif t == 'c':
                    condition |= Q(notification_content__icontains=keyword)

                elif t =='tc':
                    condition |= Q(notification_title__icontains=keyword) & Q(notification_content__icontains=keyword)


        notifications = Notification.enabled_objects.filter(notification_status=category).filter(condition).annotate(
            notification_file=Subquery(NotificationFile.objects.filter(notification=OuterRef('pk')).values('path')[:1])
        ).values(*columns)[offset:limit]

        has_next = Notification.enabled_objects.filter().filter(condition)[limit:limit + 1].exists()

        notification_info = {
            'notifications' : notifications,
            'hasNext' : has_next
        }

        return Response(notification_info)


class NotificationUpdateView(View):
    def get(self, request, id):
        notification = Notification.objects.get(id=id)
        print(notification)
        context = {
            'notification' : notification,
            'notification_file' : notification.notificationfile_set.all()
        }
        return render(request, 'notification/update.html', context)

    @transaction.atomic
    def post(self, request, id):
        data = request.POST
        file = request.FILES
        print(id)

        notification = Notification.objects.get(id=id)
        notification.notification_title = data['notification-title']
        notification.notification_content = data['notification-content']
        notification.notification_status = data['notification-status']

        notification.save(update_fields=['notification_title', 'notification_content', 'notification_status'])

        notification.notificationfile_set.all().delete()

        for key, file in request.FILES.items():
            file_instance = File.objects.create(file_size=file.size)
            NotificationFile.objects.create(file=file_instance, path=file, notification=notification)

        return redirect(notification.get_absolute_url())

templates/notification/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{#    공용으로 쓸 css 자리#}
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css">
    <link rel="icon" href="{% static 'admin/images/header-logo_RE.png' %}" />
    {% block static %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{#    {% include '' %}#}
    {% block content %}{% endblock %}
</body>
{% block js %}{% endblock %}
</html>

templates/notification/detail.html
{% extends  'notification/base.html' %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'notification/css/detail.css' %}">
{% endblock %}

{% block title %}공지사항 상세보기{% endblock %}

{% block content %}
    <div id="page-container">
        <div class="black-wrap" style="display: none"></div>
       <!-----------------바디 작업 시작------------------------------------------------->
        <div id="newContainer">
            <div id="wBoardWrap">
                <div class="wboard-wrap">
                    <div class="wboard-content">
        <!-----------------------바디 제목 부분 시작---------------------------------------->
                        <div class="article-top">
                            <div class="info">
                                <em class="user-img" style="background-image:url({% static 'notification/images/favicon.png' %})"></em>
                                <span class="user-info">관리자
                                    <br>
                                    {{ notification.created_date }}
                                </span>
                            </div>
                            <p class="title">{{ notification.notification_title }}</p>
                            {% if request.session.member.member_status == False %}
                                <a href="{% url 'notification:update' id=notification.id %}">수정하기</a>
                            {% endif %}
                            
                        </div>
                        <div class="slick-slide slick-active slick-current" id="big" aria-hidden="false" style="outline: none; width: 705px; margin-top: 92px; margin-left: 276px">
                            <div>
                                <div style="width: 100%; max-height: 100%; display: inline-block; margin-left: -158px">
                                    {% if notification.notificationfile_set.all %}
                                        {% for file in notification.notificationfile_set.all %}
                                            {% if forloop.counter0 == 0 %}
                                                {% if file.file %}
                                                    <img src="/upload/{{ file.path }}" class="lazy-load-img" id="big-img"  style="display: block; margin: 5px auto; text-align: center"/>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="notification-content-box" id="content">
                            {{ notification.notification_content }}
                        </div>
                    </div>
                    
                    <div class="wboard-btn-wrap">
                        {% if request.session.member.member_status == False %}
                            <a href="{% url 'member:admin_main_notification' %}">
                        {% else %}
                            <a href="{% url 'notification:list' %}">
                        {% endif %}
                            목록으로 돌아가기</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}

{% endblock %}

templates/notification/update.html
{% extends 'admin/base.html' %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'notification/css/write.css' %}">
{% endblock %}

{% block title %}공지사항 수정{% endblock %}

{% block content %}
    <div class="flex-column">
        <main role="main">
            <div class="container">
                <!-- 위에쪽 네비 -->
                <div class="align-items-center">
                    <nav class="col">
                        <ol class="breadcrumbs">
                            <li>
                                <a href="">관리자 페이지</a>
                            </li>
                            <li>공지 수정</li>
                        </ol>
                    </nav>
                </div>
                <div class="row">
                    <div class="lg:col-9">
                        <!-- 맨위쪽 큰 글씨 쪽 -->
                        <header class="mb-5">
                            <h1 class="h1">공지사항 수정하기</h1>
                        </header>
                        <div class="form">
                            <div></div>

                            <!-- 밑에 텍스트들 -->
                            <form action="{% url 'notification:update' id=notification.id %}" method="post" name="write=form" enctype="multipart/form-data" class="request-form">
                                {% csrf_token %}
                                <!-- 첫번쨰 텍스트 -->
                                <input name="utf8" type="hidden" />
                                <div class="form-field" style="display: block"></div>
                                <div class="form-field select optional request_ticket_form_id" style="display: block">
                                    <label for="request_issue_type_select">
                                        공지 카테고리를 선택해주세요:)
                                    </label>
                                    <a class="nesty-input" href="" style="
                                            max-width: 100%;
                                            display: none;
                                        ">프로젝트 수정/변경요청하기</a>
                                    <select name="notification-status" id="request_issue_type_select">
                                        <option value="0">
                                            커뮤니티 공지사항
                                        </option>
                                        <option value="1">
                                            원랩 공지사항
                                        </option>
                                        <option value="2">
                                            장소공유 공지사항
                                        </option>
                                        <option value="3">
                                            공모전 공지사항
                                        </option>
                                    </select>
                                </div>
                                <div class="form-field string required request_anonymous_requester_email">
                                    <label>제목 작성</label>
                                    <input
                                        name="notification-title"
                                        id="request_anonymous_requester_email"
                                        type="text"
                                        value="{{ notification.notification_title }}"
                                    />
                                </div>

                                <!-- 텍스트쪽 -->
                                <div class="form-field text required request_description">
                                    <label id="request_description_label" for="">공지사항 내용을 입력해주세요.</label>
                                    <div role="group">
                                            <textarea
                                                name="notification-content"
                                                class="tox-edit-area__iframe"
                                                cols="30"
                                                rows="10"
                                                style="width: 100%; height: 100%;
                                                resize: none;"
                                            >{{ notification.notification_content }}</textarea>
                                        </div>
                                    <input
                                        type="hidden"
                                        value="text/html"
                                        style="display: none"
                                        autocomplete="off"
                                    />
                                </div>
                                <!-- 맨밑 파일쪽 -->
                                <div class="section-content" style="margin-top: 25px;">
                                    <div class="attach-wrap">
                                    
                                        {% if notification_file %}
                                            {% for file in notification_file %}
                                                <label for="upload1" class="attach">
                                                    <img src="/upload/{{ file.path }}" class="thumbnail" style="display: block">
                                                    <div class="x" style="display: block">
                                                        <img src="{% static 'exhibition/images/x.png' %}">
                                                    </div>
                                                    <h6 class="plus" style="display: none">+</h6>
                                                    <h6 style="display: none">대표 이미지</h6>
                                                </label>   
                                            {% endfor %}
                                        {% else %}
                                            <label for="upload1" class="attach">
                                                <img src="" class="thumbnail">
                                                <div class="x">
                                                    <img src="{% static 'exhibition/images/x.png' %}">
                                                </div>
                                                <h6 class="plus">+</h6>
                                                <h6>대표 이미지</h6>
                                            </label>
                                        {% endif %}
                                    
                                            
                                    </div>
                                </div>
                                <input type="file" name="upload1" id="upload1" class="upload" style="display: none;">
                                <!-- 맨밑 제출 버튼쪽 -->
                                <input
                                        class="btn"
                                        type="submit"
                                        name="commit"
                                        value="제출"
                                        style="margin-left: 711px;"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://rawgit.com/jackmoore/autosize/master/dist/autosize.min.js"></script>
    <script src="{% static 'notification/js/write.js' %}"></script>
{% endblock %}

templates/notification/write.html
{% extends 'notification/base.html' %}

{% load static %}

{% block static %}
    <link rel="stylesheet" href="{% static 'notification/css/write.css' %}">
{% endblock %}

{% block title %}공지사항 작성{% endblock %}

{% block content %}
    <div class="flex-column">
        <main role="main">
            <div class="container">
                <!-- 위에쪽 네비 -->
                <div class="align-items-center">
                    <nav class="col">
                        <ol class="breadcrumbs">
                            <li>
                                <a href="">관리자 페이지</a>
                            </li>
                            <li>공지 등록</li>
                        </ol>
                    </nav>
                </div>
                <div class="row">
                    <div class="lg:col-9">
                        <!-- 맨위쪽 큰 글씨 쪽 -->
                        <header class="mb-5">
                            <h1 class="h1">공지사항 작성</h1>
                        </header>
                        <div class="form">
                            <div></div>

                            <!-- 밑에 텍스트들 -->
                            <form action="{% url 'notification:write' %}" method="post" name="write-form" enctype="multipart/form-data" class="request-form">
                                {% csrf_token %}
                                <!-- 첫번쨰 텍스트 -->
                                <input name="utf8" type="hidden" />
                                <div class="form-field" style="display: block"></div>
                                <div class="form-field select optional request_ticket_form_id" style="display: block">
                                    <label for="request_issue_type_select">
                                        공지 카테고리를 선택해주세요:)
                                    </label>
                                    <a class="nesty-input" href="" style="
                                            max-width: 100%;
                                            display: none;
                                        ">프로젝트 수정/변경요청하기</a>
                                    <select name="notification-status" id="request_issue_type_select">
                                        <option value="0">
                                            커뮤니티 공지사항
                                        </option>
                                        <option value="1">
                                            원랩 공지사항
                                        </option>
                                        <option value="2">
                                            장소공유 공지사항
                                        </option>
                                        <option value="3">
                                            공모전 공지사항
                                        </option>
                                    </select>
                                </div>
                                <div class="form-field string required request_anonymous_requester_email">
                                    <label>제목 작성</label>
                                    <input
                                        name="notification-title"
                                        id="request_anonymous_requester_email"
                                        type="text"
                                    />
                                </div>

                                <!-- 텍스트쪽 -->
                                <div class="form-field text required request_description">
                                    <label id="request_description_label" for="">공지사항 내용을 입력해주세요.</label>
                                    <div role="group">
                                            <textarea
                                                name="notification-content"
                                                class="tox-edit-area__iframe"
                                                cols="30"
                                                rows="10"
                                                style="width: 100%; height: 100%;
                                                resize: none;"
                                            ></textarea>
                                        </div>
                                    <input
                                        type="hidden"
                                        value="text/html"
                                        style="display: none"
                                        autocomplete="off"
                                    />
                                </div>
                                <!-- 맨밑 파일쪽 -->
                                <div class="section-content" style="margin-top: 25px;">
                                    <div class="attach-wrap">
                                        <label for="upload1" class="attach">
                                            <img src="" class="thumbnail">
                                            <div class="x">
                                                <img src="{% static 'exhibition/images/x.png' %}">
                                            </div>
                                            <h6 class="plus">+</h6>
                                            <h6>대표 이미지</h6>
                                        </label>
                                    </div>
                                </div>
                                <input type="file" name="upload1" id="upload1" class="upload" style="display: none;">
                                <!-- 맨밑 제출 버튼쪽 -->
                                <input
                                        class="btn"
                                        type="submit"
                                        name="commit"
                                        value="제출"
                                        style="margin-left: 711px;"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

{% block js %}
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <script src="https://rawgit.com/jackmoore/autosize/master/dist/autosize.min.js"></script>
    <script src="{% static 'notification/js/write.js' %}"></script>
{% endblock %}