ai/urls.py
from django.urls import path

app_name = 'ai'

urlpatterns = [
    # path('detail/', AlarmDetailView.as_view(), name='alarm-detail'),
    # path('detail/api/<int:page>/', AlarmPagiNationAPIView.as_view()),
    # path('detail/agree/api/', AlarmAgreeAPIView.as_view()),
    # path('detail/deny/api/', AlarmDenyAPIView.as_view()),
    # path('detail/cancel/api/', AlarmCancelAPIView.as_view())
]

oneLabProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from exhibition.views import ExhibitionFileDownloadView
from oneLabProject.views import MainView
from share.views import ShareDownloadView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('oauth.urls')),
    path('onelab/', include('onelab.urls')),
    path('community/', include('community.urls')),
    path('myPage/', include('myPage.urls')),
    path('point/', include('point.urls')),
    path('alarm/', include('alarm.urls')),
    path('replies/', include('reply.urls')),
    path('place/', include('place.urls')),
    path('school/', include('school.urls')),
    path('review/', include('review.urls')),
    path('share/', include('share.urls')),
    path('upload/<path:file_path>', ShareDownloadView.as_view(), name='download'),
    path('exhibition/', include('exhibition.urls')),
    path('upload/<path:file_path>/', ExhibitionFileDownloadView.as_view(), name='exhibition-down'),
    path('notification/', include('notification.urls')),
    path('', MainView.as_view(), name='main'),
    path('ai/api/', include('ai.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

place/urls.py
from django.urls import path

from place.views import PlaceDetailView, PlaceListView, PlaceWriteView, PlaceUpdateView, \
    PlaceDeleteView, PlaceReviewListView, PlaceReviewListAPIView, PlaceLikeView, PlaceListAPIView

app_name = 'place'

urlpatterns = [
    path('detail/<int:id>/', PlaceDetailView.as_view(), name='detail'),
    path('list/', PlaceListView.as_view(), name='list'),
    path('list/<int:page>/', PlaceListAPIView.as_view(), name='list'),
    path('write/', PlaceWriteView.as_view(), name='write'),
    # path('update/', PlaceUpdateView.as_view(), name='update'),
    path('update/<int:id>', PlaceUpdateView.as_view(), name='update'),
    path('delete/', PlaceDeleteView.as_view(), name='delete'),
    path('review/list/<int:place_id>/<int:page>/', PlaceReviewListAPIView.as_view(), name='review_list_api'),
    path('review/list/', PlaceReviewListView.as_view(), name='review_list'),
    path('like/', PlaceLikeView.as_view(), name='like'),
]

review/urls.py
from django.urls import path

from review.views import ReviewPlaceWriteView, ReviewShareWriteView

app_name = 'review'

urlpatterns = [
    path('place/write/', ReviewPlaceWriteView.as_view(), name='place-write'),
    path('share/write/', ReviewShareWriteView.as_view(), name='share-write')
]

review/models.py
from django.db import models

from file.models import File
from member.models import Member
from oneLabProject.models import Period
from review.managers import ReviewManager


class Review(Period):
    review_content = models.TextField(null=False, blank=False)
    review_rating = models.FloatField(null=False, blank=False, default=0.0)
    member = models.ForeignKey(Member, on_delete=models.PROTECT, null=False)
    review_post_status = models.BooleanField(null=False, default=True)

    objects = models.Manager()
    enabled_objects = ReviewManager()

    class Meta:
        db_table = 'tbl_review'
        ordering = ['-id']

class ReviewFile(Period):
    file = models.ForeignKey(File, primary_key=True, on_delete=models.PROTECT, null=False)
    path = models.ImageField(null=False, blank=False, upload_to='review/%Y/%m/%d')
    review = models.ForeignKey(Review, on_delete=models.PROTECT, null=False)

    class Meta:
        db_table = 'tbl_review_file'

review/views.py
from django.db import transaction
from django.shortcuts import render, redirect
from django.views import View

from file.models import File
from member.models import Member
from place.models import PlaceReview, Place
from review.models import Review, ReviewFile
from share.models import Share, ShareReview


class ReviewPlaceWriteView(View):
    def get(self, request):
        place = Place.objects.get(id=request.GET['id'])
        return render(request, 'review/place-write.html',{'place': place})

    @transaction.atomic
    def post(self, request):
        data = request.POST
        place_id = data["place-id"]

        # input 태그 하나 당 파일 1개 일 떄
        file = request.FILES

        member = Member.objects.get(id=request.session['member']['id'])

        data = {
            'review_content': data['review-content'],
            'review_rating': data['review-rating'],
            'member': member,
        }
        review = Review.objects.create(**data)

        for key, file in file.items():
            file_instance = File.objects.create(file_size=file.size)
            ReviewFile.objects.create(review=review, file=file_instance, path=file)

        place = Place.objects.get(id=place_id)
        place_review_info = {
            'review': review,
            'place': place
        }
        PlaceReview.objects.create(**place_review_info)

        return redirect(f'/place/review/list?place_id={place_id}')

class ReviewShareWriteView(View):
    def get(self, request):
        share = Share.objects.get(id=request.GET['id'])
        return render(request, 'review/share-write.html',{'share': share})

    @transaction.atomic
    def post(self, request):
        data = request.POST
        share_id = data["share-id"]

        # input 태그 하나 당 파일 1개 일 떄
        file = request.FILES

        member = Member.objects.get(id=request.session['member']['id'])

        data = {
            'review_content': data['review-content'],
            'review_rating': data['review-rating'],
            'member': member,
        }
        review = Review.objects.create(**data)

        for key, file in file.items():
            file_instance = File.objects.create(file_size=file.size)
            ReviewFile.objects.create(review=review, file=file_instance, path=file)

        share = Share.objects.get(id=share_id)
        share_review_info = {
            'review': review,
            'share': share
        }
        ShareReview.objects.create(**share_review_info)

        return redirect(f'/share/review/list?share_id={share_id}')

templates/review/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{#     헤더, 푸터 css경로#}
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-footer.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-header.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-header-all.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-header-login.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-header-login-one.css' %}" />
{#favicon 경로#}
    <link rel="shortcut icon" href="{% static 'public/images/real-favicon.png' %}">
    {% block static %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="modal">
        <div class="warn-modal">
            <div id="content-wrap"></div>
        </div>
    </div>
    {#헤더 html 경로#}
    {% include 'header/main-page-header-login.html' %}
    
    {% block content %}{% endblock %}
    
    {#푸터 경로#}
</body>
{% include 'header/main-page-footer.html' %}
<script src="{% static 'public/js/modals.js' %}"></script>
    {% block js %}{% endblock %}
</html>

templates/review/place-write.html
{% extends 'review/base.html' %}
{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'review/css/write.css' %}">
<link rel="stylesheet" href="{% static 'public/css/main-page-footer.css' %}">
{% endblock %}
{% block title %}후기 작성페이지{% endblock %}
{% block content %}
    <!-- 메인 시작 -->
        <main class="review-main">
            <div class="container" id="page-container">
                <div class="review-form-container">
                    <div class="review-form-wrapper">
                        <header class="review-title">
                            <h1>후기 등록</h1>
                        </header>
                        <div class="form-inner">
                            <form action="{% url 'review:place-write' %}" method="POST" id="new-review-request" class="review-request-form" name="commit" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="utf-8" autocomplete="off">
                                <div class="form-field-select-product" style="display: block;">
                                    <label for="registration-review" class="select-product-text">후기를 작성할 상품명</label>
                                    <input type="hidden" name="place-id" value="{{ place.id }}">
                                    <a class="select-product-box" style="max-width: 100%;">{{ place.place_title }}</a>
                                </div>
                                <div class="form-field-review-score">
                                    <label for="" class="select-review-score">상품 별점</label>
                                    <div class="review-score-wrap">
                                        <div class="review-score-box">
                                            <div class ="star-rating">
                                                <span class="star on" style="cursor: pointer;" value="1">
                                                    <input type="hidden" value="1">
                                                </span>
                                                <span class="star" style="cursor: pointer;" value="2">
                                                    <input type="hidden" value="2">
                                                </span>
                                                <span class="star" style="cursor: pointer;" value="3">
                                                    <input type="hidden" value="3">
                                                </span>
                                                <span class="star" style="cursor: pointer;" value="4">
                                                    <input type="hidden" value="4">
                                                </span>
                                                <span class="star" style="cursor: pointer;" value="5">
                                                    <input type="hidden" value="5">
                                                </span>
                                              </div>
                                            <div class="choice-text none">선택해주세요</div>
                                            <div class="choice-text one" style="display: none;">1점(별로에요)</div>
                                            <div class="choice-text two" style="display: none;">2점(그저 그래요)</div>
                                            <div class="choice-text three" style="display: none;">3점(보통이에요)</div>
                                            <div class="choice-text four" style="display: none;">4점(괜찮아요)</div>
                                            <div class="choice-text five" style="display: none;">5점(좋아요)</div>
                                        </div>
                                    </div>
                                </div>
                                <!-- 후기글 작성 섹션 -->
                                <div class="form-field-review-text">
                                    <label for="" class="write-reivew-text">후기를 작성해 주세요</label>
                                    <textarea name="review-content" id="" cols="30" rows="10" style="resize: none;"></textarea>
                                </div>
                                <!-- 후기 사진 첨부 섹션 -->
                                <div class="form-field-file">
                                    <label for="" class="file-upload">첨부 파일
                                        <span class="optional">(선택 사항)</span>
                                    </label>
                                    <div class="upload-dropzone">
                                        <input type="file" name="upload-file" id="file-input">
                                        <span>
                                            <a href="">이미지 추가</a>
                                        </span>
                                    </div>
                                    <div class="upload-error" style="display: none;">
                                        <span>이미지 파일만 업로드 가능합니다.</span>
                                    </div>
                                    <!-- 업로드 시, 파일 미리보기 되는 부분 -->
                                    <ul class="upload-pool">
                                        <li class="upload-item" id="file-list">
                                            <button class="cancel-upload" style="display: none;">X</button>
                                            <img id="thumbnail" src="#" alt="Thumbnail" style="display: none;" width="100px">
                                        </li>
                                    </ul>
                                </div>
                                <input type="submit" name="commit" class="submit-btn" value="제출">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="{% static 'review/js/write.js' %}"></script>
    <script src="{% static 'place/js/review-list.js' %}"></script>
    <script>
        let rate = 1
        // 별점 선택시, 해당 value값 선택
        const stars = document.querySelectorAll('.star')
        stars.forEach((star) => {
            star.addEventListener('click', function (e){
                stars.forEach(((star) => {
                    const input = star.children;
                    input[0].setAttribute('name', '')
                }))
                const input = star.children;
                rate = input[0].value;
                input[0].setAttribute('name', 'review-rating')
            })
        })
        {#document.querySelector('.submit-btn').click(#}
        {#    {% url 'review:write' %}#}
        {#)#}
    </script>
{% endblock %}

templates/review/share-write.html
{% extends 'review/base.html' %}
{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'review/css/write.css' %}">
<link rel="stylesheet" href="{% static 'public/css/main-page-footer.css' %}">
{% endblock %}
{% block title %}후기 작성페이지{% endblock %}
{% block content %}
    <!-- 메인 시작 -->
        <main class="review-main">
            <div class="container" id="page-container">
                <div class="review-form-container">
                    <div class="review-form-wrapper">
                        <header class="review-title">
                            <h1>후기 등록</h1>
                        </header>
                        <div class="form-inner">
                            <form action="{% url 'review:share-write' %}" method="POST" id="new-review-request" class="review-request-form" name="commit" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="utf-8" autocomplete="off">
                                <div class="form-field-select-product" style="display: block;">
                                    <label for="registration-review" class="select-product-text">후기를 작성할 상품명</label>
                                    <input type="hidden" name="share-id" value="{{ share.id }}">
                                    <a class="select-product-box" style="max-width: 100%;">{{ share.share_title }}</a>
                                </div>
                                <div class="form-field-review-score">
                                    <label for="" class="select-review-score">상품 별점</label>
                                    <div class="review-score-wrap">
                                        <div class="review-score-box">
                                            <div class ="star-rating">
                                                <span class="star on" style="cursor: pointer;" value="1">
                                                    <input type="hidden" value="1">
                                                </span>
                                                <span class="star" style="cursor: pointer;" value="2">
                                                    <input type="hidden" value="2">
                                                </span>
                                                <span class="star" style="cursor: pointer;" value="3">
                                                    <input type="hidden" value="3">
                                                </span>
                                                <span class="star" style="cursor: pointer;" value="4">
                                                    <input type="hidden" value="4">
                                                </span>
                                                <span class="star" style="cursor: pointer;" value="5">
                                                    <input type="hidden" value="5">
                                                </span>
                                              </div>
                                            <div class="choice-text none">선택해주세요</div>
                                            <div class="choice-text one" style="display: none;">1점(별로에요)</div>
                                            <div class="choice-text two" style="display: none;">2점(그저 그래요)</div>
                                            <div class="choice-text three" style="display: none;">3점(보통이에요)</div>
                                            <div class="choice-text four" style="display: none;">4점(괜찮아요)</div>
                                            <div class="choice-text five" style="display: none;">5점(좋아요)</div>
                                        </div>
                                    </div>
                                </div>
                                <!-- 후기글 작성 섹션 -->
                                <div class="form-field-review-text">
                                    <label for="" class="write-reivew-text">후기를 작성해 주세요</label>
                                    <textarea name="review-content" id="" cols="30" rows="10" style="resize: none;"></textarea>
                                </div>
                                <!-- 후기 사진 첨부 섹션 -->
                                <div class="form-field-file">
                                    <label for="" class="file-upload">첨부 파일
                                        <span class="optional">(선택 사항)</span>
                                    </label>
                                    <div class="upload-dropzone">
                                        <input type="file" name="upload-file" id="file-input">
                                        <span>
                                            <a href="">이미지 추가</a>
                                        </span>
                                    </div>
                                    <div class="upload-error" style="display: none;">
                                        <span>이미지 파일만 업로드 가능합니다.</span>
                                    </div>
                                    <!-- 업로드 시, 파일 미리보기 되는 부분 -->
                                    <ul class="upload-pool">
                                        <li class="upload-item" id="file-list">
                                            <button class="cancel-upload" style="display: none;">X</button>
                                            <img id="thumbnail" src="#" alt="Thumbnail" style="display: none;" width="100px">
                                        </li>
                                    </ul>
                                </div>
                                <input type="submit" name="commit" class="submit-btn" value="제출">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
{% endblock %}
{% block js %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="{% static 'review/js/write.js' %}"></script>
    <script src="{% static 'place/js/review-list.js' %}"></script>
    <script>
        let rate = 1
        // 별점 선택시, 해당 value값 선택
        const stars = document.querySelectorAll('.star')
        stars.forEach((star) => {
            star.addEventListener('click', function (e){
                stars.forEach(((star) => {
                    const input = star.children;
                    input[0].setAttribute('name', '')
                }))
                const input = star.children;
                rate = input[0].value;
                input[0].setAttribute('name', 'review-rating')
            })
        })
        {#document.querySelector('.submit-btn').click(#}
        {#    {% url 'review:write' %}#}
        {#)#}
    </script>
{% endblock %}