ai/urls.py
from django.urls import path

app_name = 'ai'

urlpatterns = [
    # path('detail/', AlarmDetailView.as_view(), name='alarm-detail'),
    # path('detail/api/<int:page>/', AlarmPagiNationAPIView.as_view()),
    # path('detail/agree/api/', AlarmAgreeAPIView.as_view()),
    # path('detail/deny/api/', AlarmDenyAPIView.as_view()),
    # path('detail/cancel/api/', AlarmCancelAPIView.as_view())
]

oneLabProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from exhibition.views import ExhibitionFileDownloadView
from oneLabProject.views import MainView
from share.views import ShareDownloadView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('member/', include('member.urls')),
    path('accounts/', include('allauth.urls')),
    path('oauth/', include('oauth.urls')),
    path('onelab/', include('onelab.urls')),
    path('community/', include('community.urls')),
    path('myPage/', include('myPage.urls')),
    path('point/', include('point.urls')),
    path('alarm/', include('alarm.urls')),
    path('replies/', include('reply.urls')),
    path('place/', include('place.urls')),
    path('school/', include('school.urls')),
    path('review/', include('review.urls')),
    path('share/', include('share.urls')),
    path('upload/<path:file_path>', ShareDownloadView.as_view(), name='download'),
    path('exhibition/', include('exhibition.urls')),
    path('upload/<path:file_path>/', ExhibitionFileDownloadView.as_view(), name='exhibition-down'),
    path('notification/', include('notification.urls')),
    path('', MainView.as_view(), name='main'),
    path('ai/api/', include('ai.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

place/urls.py
from django.urls import path

from place.views import PlaceDetailView, PlaceListView, PlaceWriteView, PlaceUpdateView, \
    PlaceDeleteView, PlaceReviewListView, PlaceReviewListAPIView, PlaceLikeView, PlaceListAPIView

app_name = 'place'

urlpatterns = [
    path('detail/<int:id>/', PlaceDetailView.as_view(), name='detail'),
    path('list/', PlaceListView.as_view(), name='list'),
    path('list/<int:page>/', PlaceListAPIView.as_view(), name='list'),
    path('write/', PlaceWriteView.as_view(), name='write'),
    # path('update/', PlaceUpdateView.as_view(), name='update'),
    path('update/<int:id>', PlaceUpdateView.as_view(), name='update'),
    path('delete/', PlaceDeleteView.as_view(), name='delete'),
    path('review/list/<int:place_id>/<int:page>/', PlaceReviewListAPIView.as_view(), name='review_list_api'),
    path('review/list/', PlaceReviewListView.as_view(), name='review_list'),
    path('like/', PlaceLikeView.as_view(), name='like'),
]

place/models.py
from datetime import date

from django.db import models
from django.utils.timezone import now

from file.models import File
from like.models import Like
from oneLabProject.models import Period
from place.managers import PlaceManager, PlaceReviewManager
from point.models import Point
from review.models import Review
from school.models import School


class Place(Period):

    place_title = models.TextField(null=False, blank=False)
    place_content = models.TextField(null=False, blank=False)
    place_points = models.BigIntegerField(null=True, default=1000)
    # False=결제 전, True=결제완료
    place_order_status = models.BooleanField(null=False, default=False)
    place_review_rating = models.FloatField(null=False, default=0.0)
    place_image_file = models.ImageField(null=False, blank=False, upload_to='')
    school = models.ForeignKey(School, on_delete=models.PROTECT, null=False)
    place_date = models.DateField(null=False, blank=False, default=now)
    place_ask_email = models.CharField(null=False, max_length=300)
    place_url = models.CharField(null=False, max_length=300, default='http://localhost:')
    place_post_status = models.BooleanField(default=True, null=False)

    objects = models.Manager()
    enabled_objects = PlaceManager()

    class Meta:
        db_table = 'tbl_place'
        ordering = ['-id']

    def get_absolute_url(self):
        return f'/place/detail/?id={self.id}'

class PlaceFile(Period):
    file = models.ForeignKey(File, primary_key=True, on_delete=models.PROTECT, null=False)
    path = models.ImageField(null=False, blank=False, upload_to='place/%Y/%m/%d')
    place = models.ForeignKey(Place, on_delete=models.PROTECT, null=False)

    class Meta:
        db_table = 'tbl_place_file'

class PlaceLike(Period):
    like = models.ForeignKey(Like, primary_key=True, on_delete=models.PROTECT, null=False)
    place = models.ForeignKey(Place, on_delete=models.PROTECT, null=False, default=1)

    class Meta:
        db_table = 'tbl_place_like'

class PlacePoints(Period):
    points = models.ForeignKey(Point, primary_key=True, on_delete=models.PROTECT, null=False)
    place = models.ForeignKey(Place, on_delete=models.PROTECT, null=False)

    class Meta:
        db_table = 'tbl_place_points'

class PlaceReview(Period):
    review = models.ForeignKey(Review, primary_key=True, on_delete=models.PROTECT, null=False)
    place = models.ForeignKey(Place, on_delete=models.PROTECT, null=False)

    objects = models.Manager()
    enabled_objects = PlaceReviewManager()
    class Meta:
        db_table = 'tbl_place_review'

place/views.py
import math
from decimal import Decimal

from django.core.paginator import Paginator
from django.db import transaction
from django.db.models import Avg, F, Q, Sum
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
import json
from rest_framework.views import APIView

from community.models import Community
from file.models import File
from like.models import Like
from member.models import Member, MemberFile
from onelab.models import OneLab
from place.models import PlaceReview, PlaceLike, PlacePoints
from place.models import Place, PlaceFile
from placeMember.models import PlaceMember
from point.models import Point
from review.models import Review
from school.models import School
from share.models import Share
from oneLabProject.settings import MEDIA_URL
from university.models import University


class PlaceDetailView(View):
    def get(self, request, id):
        post = Place.objects.get(id=id)

        school_member = School.objects.get(member=post.school)
        post_list = Place.enabled_objects.filter(school=school_member).order_by('-id')
        page = request.GET.get('page', 1)
        paginator = Paginator(post_list, 4)
        posts = paginator.page(page)

        # 이미지 파일 가져오기
        for p in posts:
            first_file = p.placefile_set.first()
            if first_file:
                # 파일이 있으면 파일의 경로를 기반으로 URL 생성
                p.image_url = f"{MEDIA_URL}{first_file.path}"
            else:
                p.image_url = None

        # 리뷰 평균과 개수
        reviews = PlaceReview.enabled_objects.filter(place_id=post.id)
        if len(reviews) > 0:
            review_count = reviews.count()
            review_avg_decimal = reviews.aggregate(avg_rating=Avg('review__review_rating'))['avg_rating']
            review_avg_rounded = Decimal(review_avg_decimal).quantize(Decimal('0.1'))
        else:
            review_count = 0
            review_avg_rounded = 0.0

        # 좋아요 수
        place_like_count = PlaceLike.objects.filter(place=post).count()

        # 회원이 좋아요를 한 상태인지
        member = Member.objects.get(id=request.session['member']['id'])
        place_likes = PlaceLike.objects.filter(place=post)
        member_like = False
        for place_like in place_likes:
            try:
                # 해당 Like 객체
                like_object = Like.objects.get(member=member, like_status=True, id=place_like.like_id)
                # 해당 Like 객체가 존재
                member_like = True
            except Like.DoesNotExist:
                # 해당 Like 객체가 없음
                member_like = False

        context = {
            'place': post,
            'place_files': list(post.placefile_set.all()),
            'posts': posts,
            'review_count': review_count,
            'review_avg_rounded': review_avg_rounded,
            'place_like_count': place_like_count,
            'member_like': member_like,
        }
        return render(request, 'place/detail.html', context)

    # -------------결제 부분 주석 포함 87번째 줄부터 추가하시면 됩니다!!!--------------------------------------------------#
    def post(self, request, id):
        # post = 해당 장소 공유 아이디
        post = Place.objects.get(id=id)
        # price = 장소의 포인트 가격
        school = post.school_id
        price = post.place_points
        # place_member = 해당 장소를 공유한 학교 회원 아이디
        place_member = post.school_id
        # 이게 필요한가? 이미 위에서 장소의 학교회원 아이디를 받았는데
        place_member_id = School.objects.get(member_id=school)
        # 그냥 디버깅 용으로 선언한 거임
        print(place_member_id)  # --> 1번 아이디의 학교멤버
        # 학교 회원에서 실제 멤버 아이디를 가져옴
        member = place_member_id.member_id  # --> 3번 아이디의 멤버
        # point 모델에 적립(status=3), 가격 , 멤버를 추가함
        Point.objects.create(member_id=member, point_status=3, point=price)
        # 학교회원의 적립 포인트를 출력한다.
        print(Point.objects.filter(member_id=member, point_status=3).aggregate(Sum('point'))['point__sum'])
        # 구매하려는 대학생 회원 아이디를 가져온다.
        member_id = request.session['member']['id']
        print(member_id)
        university = University.objects.get(member_id=member_id)
        print(university)
        # 장소대여 포인트 모델 을 불러온다.
        place_price = PlacePoints.objects.filter(place_id=post.id)
        # 실제 대학생의 포인트에서 장소대여 포인트 값이 빠져야함
        university.university_member_points -= price
        # 적용된 값 저장
        university.save()

        # 장소대여의 결제 status가 1로 바뀐다.
        place = Place.objects.update(place_order_status=1)

        # point 모델에 사용된 포인트 정보를 추가한다.
        datas = {
            'point': price,
            'point_status': 2,
            'member_id': member_id
        }
        point = Point.objects.create(**datas)
        # place point 모델에 정보를 추가한다. (이미 구매한 사용자면 조회)
        place_data = {
            'place_id': id,
            'points_id': point.id
        }
        PlacePoints.objects.get_or_create(**place_data)
        # ------------------------------결제 부분 완료---------------------------------#
        # --------------------------------멤버 참여 기능 시작---------------------------#
        join_data = {
            'place_member_status': 0,
            'university_id': request.session['member']['id'],
            'place_id': post.id
        }
        PlaceMember.objects.get_or_create(**join_data)
        # --------------------------------멤버 참여 기능 완료---------------------------#
        return redirect('/myPage/main/')


# 좋아요
class PlaceLikeView(View):
    def post(self, request):
        if request.method == 'POST' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
            # JSON 데이터 파싱
            data = json.loads(request.body)
            place_id = data.get('place_id')
            print(place_id)
            # 해당 place_id 가진 게시글 가져오기
            place = Place.objects.get(id=place_id)
            # 세션에 들어있는 회원
            member = Member.objects.get(id=request.session['member']['id'])

            try:
                # 해당 회원이 이 게시글에 대해 좋아요를 한 경우
                place_like = PlaceLike.objects.get(place=place, like__member=member)
                if place_like.like.like_status:
                    # 이미 좋아요한 경우, 좋아요 취소
                    place_like.like.like_status = False
                    place_like.like.save()  # like_status를 False로 변경
                    place_like.delete()  # 좋아요 삭제
                else:
                    # 이미 좋아요를 취소한 경우
                    # like_status를 True로 변경하여 다시 좋아요를 한 것으로 처리
                    place_like.like.like_status = True
                    place_like.like.save()  # like_status를 True로 변경
            except PlaceLike.DoesNotExist:
                # 해당 회원이 이 게시글에 대해 좋아요를 하지 않은 경우
                # 좋아요 생성
                like = Like.objects.create(member=member, like_status=True)
                place_like = PlaceLike.objects.create(place=place, like=like)

            # 업데이트된 좋아요 수 응답
            place_like_count = PlaceLike.objects.filter(place=place).count()
            return JsonResponse({'like_count': place_like_count})

        # AJAX 요청이 아닌 경우
        return render(request, 'place/detail.html')
class PlaceWriteView(View):
    def get(self, request):
        member = Member.objects.get(id=request.session['member']['id'])
        school_member = School.objects.get(member=member)

        # 마이 포인트
        if len(list(Point.objects.filter(member=member, point_status=3))) > 0:
            point = Point.objects.filter(member=member, point_status=3).aggregate(Sum('point'))['point__sum']
        else:
            point = Point.objects.create(member=member, point_status=3)

        # 마이 포스트 수
        places = Place.enabled_objects.filter(school=school_member).values('place_title', 'id')
        total_post_count = places.count()

        data = {
            'point': point,
            'total_post_count': total_post_count,
            'places': places,
        }
        return render(request, 'place/write.html', data)

    @transaction.atomic
    def post(self, request):
        data = request.POST
        # input 태그 하나에 여러 파일일 때(multiple), getlist('{input태그 name값}')
        files = request.FILES.getlist('upload-file')

        # input 태그 하나 당 파일 1개 일 떄
        # file = request.FILES

        member = Member.objects.get(id=request.session['member']['id'])
        school_member = School.objects.get(member=member)

        data = {
            'place_title': data['place-title'],
            'place_points': data['place-points'],
            'place_date': data['place-date'],
            'place_content': data['place-content'],
            'place_ask_email': data['place-ask-email'],
            'place_url': data['place-url'],
            'school': school_member
        }

        place = Place.objects.create(**data)

        for file in files:
            # 업로드된 파일을 File 모델에 저장
            file_instance = File.objects.create(file_size=file.size)
            PlaceFile.objects.create(place=place, file=file_instance, path=file)

        return redirect(reverse('place:detail', kwargs={'id': place.id}))

class PlaceUpdateView(View):
    def get(self, request, id):
        member = Member.objects.get(id=request.session['member']['id'])
        school_member = School.objects.get(member=member)

        # 마이 포인트
        if len(list(Point.objects.filter(member=member, point_status=3))) > 0:
            point = Point.objects.filter(member=member, point_status=3).aggregate(Sum('point'))['point__sum']
        else:
            point = Point.objects.create(member=member, point_status=3)

        # 마이 포스트 수
        places = Place.enabled_objects.filter(school=school_member).values('place_title', 'id')
        total_post_count = places.count()

        post = Place.objects.get(id=id)
        # update_url 생성
        update_url = reverse('place:update', args=[id])
        place_content = post.place_content.strip()
        context = {
            'place': post,

templates/place/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
{#     헤더, 푸터 css경로#}
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-footer.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-header.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-header-all.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-header-login.css' %}" />
    <link rel="stylesheet" href="{% static 'member/css/header/main-page-header-login-one.css' %}" />
    <link rel="stylesheet" href="{% static 'public/css/modal.css'%}">
{#favicon 경로#}
    <link rel="shortcut icon" href="{% static 'public/images/real-favicon.png' %}">
    {% block static %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="modal">
        <div class="warn-modal">
            <div id="content-wrap"></div>
        </div>
    </div>
    {#헤더 html 경로#}
{#    {% include 'header/main-page-header.html' %}#}
    {% block content %}{% endblock %}
    {#푸터 경로#}
</body>
<script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
<script src="{% static 'public/js/modals.js' %}"></script>
    {% block js %}{% endblock %}
</html>

templates/place/list.html
{#헤더 경로#}
{% extends 'place/base.html' %}
{% load static %}
{% block static %}
<link rel="stylesheet" href="{% static 'place/css/list.css' %}">
<link rel="stylesheet" href="{% static 'public/css/main-page-footer.css' %}">
<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
{% endblock %}
{% block title %}장소공유 목록{% endblock %}
{% block content %}
    {% if request.session.member %}
        {% include  "header/main-page-header-login.html"%}
    {% else %}
        {% include "header/main-page-header-all.html" %}
    {% endif %}
    <div id="page-container">
            <main id="main-app">
                <div></div>
                <div class="ain-wrapper-content">
                    <div></div>
                    <div class="desktop-search-result-container">
                        <!-- 검색결과 쪽 -->
                        <div class="desktop-search-result-head-container">
                            <div class="desktop-search-result-keyword">장소공유</div>
                            <h2>목록</h2>
                            <div class="desktop-search-result-number">{{ place_total_count }}</div>
                            <div class="desktop-search-result-unit">개</div>
                            <hr />
                        </div>

                        <!-- 전체 펀딩 오픈예정 쪽 -->
                        <div class="DesktopSearchResult_tabContainer">
                            <ul class="SearchResultTabs_tabContainer">
                                <button type="button" class="Tab_tab Tab_first Tab_active Tab_rectangle Tab_sm">
                                    <span>전체</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>서울</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>경기</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>인천</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>울산</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>대구</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>광주</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>대전</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>부산</span>
                                </button>
                                <button type="button" class="Tab_tab Tab_first Tab_rectangle Tab_sm">
                                    <span>제주</span>
                                </button>
{#                                <a href="{% url 'place:write' %}">#}
{#                                    <button type="button" class="Tab_tab Tab_rectangle Tab_sm tab_end">#}
{#                                        <span>글 쓰기</span>#}
{#                                    </button>#}
{#                                </a>#}
                            </ul>
                        </div>

                        <!-- 목록 쪽 -->
                        <div class="SearchResult_container">
                            <!-- ad banner쪽 -->
                            <div class="AdBanner_container">
                                <div class="banner_eventBanner" style="background-color: rgb(210, 217, 222)">
                                    <div class="banner_adBadge">AD</div>
                                    <a href="https://www.wadiz.kr/web/campaign/detail/230063?acid=10047924&_refer_section_st=SPA_1" class="banner_link">
                                        <div class="banner_inner">
                                            <div class="banner_contents" style="background-image: url('https://cdn1.wadiz.kr/images/20240131/1706693471860.png/wadiz/optimize')">
                                                <div class="banner_text">
                                                    <p>9가지 솔루션 제공으로</p>
                                                    <strong>편안한 무중력 쿠셔닝슈즈</strong>
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>

                            <!-- 목록 페이지 쪽 -->
                            <div class="search-result-card-container">
                                <div class="css-dlxsy">
                                    <div class="css-uhtu">
                                        <div class="swiper-container">
                                            <div class="swiper-wrapper" style="display: flex; flex-wrap: wrap;">

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                        </div>
                        <div></div>
                    </div>
                </div>
                <div class="board-footer">
                    <div class="pagination">
                        <!-- 모바일용 버튼 -->
                        <button class="prev-page-icon mobile-only">
                            <span class="text-hidden">이전 목록</span>
                        </button>
                        <div class="page">
                            <!-- 모바일용 페이지 리스트 -->
                            <div class="mobile-only">
                                <span class="current-count">1</span>
                                /
                                <span class="total-count">
                                    <span>122</span>
                                    페이지
                                </span>
                            </div>
                            <div class="desktop-only">
                                <!-- 데스크탑용 버튼 -->
                                <button class="prev-page-icon">
                                    <span class="text-hidden">이전 목록</span>
                                </button>
                                <!-- 데스크탑용 페이지 리스트 -->
                                <a href="" class="current">1</a>
                                <a href="" class="">2</a>
                                <a href="">3</a>
                                <a href="">4</a>
                                <a href="">5</a>
                                <a href="">6</a>
                                <!-- 데스크탑용 버튼 -->
                                <button class="next-page-icon">
                                    <span class="text-hidden">다음 목록</span>
                                </button>
                            </div>
                        </div>
                        <!-- 모바일용 버튼 -->
                        <button class="next-page-icon mobile-only">
                            <span class="text-hidden">다음 목록</span>
                        </button>
                    </div>

                    <div aria-hidden="true" style="position: relative; left: 0; bottom: 48px; width: 100%;"></div>
                </div>
            </main>
    {% include  "header/main-page-footer.html"%}
        </div>
{% endblock %}
{% block js %}
    <script>
        const placeFilePath = "{{ place.placefile_set.first.path.url }}";
        const place_id = '{{ place_id }}'
        const csrfToken = '{{ csrf_token }}'
        const jsonData = JSON.stringify({'place_id': place_id})

    </script>
    <script src="{% static 'place/js/list.js' %}"></script>
{% endblock %}